### ISSUE TITLE
Code mismatch with paper

### ISSUE THREAD

**Issue by yumath** [XLearning-SCU/2023-CVPR-FPL#1]
Equation 5 in paper of weighting function，gamma is within exp() function.
https://github.com/XLearning-SCU/2023-CVPR-FPL/blob/4d7b39b287bfb4d58615f73c2c15032133440676/codes/utils/util.py#L493
https://github.com/XLearning-SCU/2023-CVPR-FPL/blob/4d7b39b287bfb4d58615f73c2c15032133440676/codes/utils/util.py#L499
but in the code, it is y alpha within exp funtion.
So, which one is correct hyper-parameters?

**Comment by YBGou** [comment]
Thanks! We find the symbols are mismatched in the code and paper. "gamma" in the code is corresponding to the $\alpha$ in the paper, e.g., "gamma_sp=0.5" in the code corresponds to $\alpha_{sp}=0.5$ in the paper.

**Comment by yumath** [comment]
@YBGou thanks very much!
